### ISSUE TITLE
Develop user interface

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-map#1]

**Comment by chartgerink** [comment]
Does this also include design or will we track that separately?

**Comment by Bisaloo** [comment]
Yes, in my mind it includes design but as the lead on this task, feel free to break it down in smaller steps, use this issue as a meta-issue, or anything else :+1:

**Comment by Bisaloo** [comment]
This is available in https://github.com/epiverse-connect/epiverse-search-frontend. I'm closing this generic issue in favour of more focused issues for specific requests or suggestions.
