### ISSUE TITLE
What do links  (= network edges) / distance between packages represent?

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-map#2]
We need to decide what the links in the network mean. Why would two tools have a link between them? Why would two tools be close to on another?

Some potential ideas to discuss:

- "Interoperability", as in https://github.com/epiverse-connect/NetworkViz, but this is difficult to quantify, or even determine in a binary way. Even more automatically.
- Dependency relationships. This tells us how the ecosystem is designed from a technical scaffolding point of view. This is easy to determine, with different strengths of dependency (`Depends`/`Imports` vs `Suggests`). But packages can be related (same goal, same authors, part of the same pipeline) without depending on one another. This is also difficult to expand to non-R tools.
- Position in the data pipeline. This might be determined by using NLP on package descriptions or vignettes

**Comment by chartgerink** [comment]
My preference would be to work outward from concrete to less concrete. I would rank order the ideas as follows:

1. Dependencies
2. Interoperability
3. Position in the pipeline

The dependencies are the clearest and most well defined, which I think at this stage would be a great start for a minimum viable version. We can also expand this concept to other languages where needed (python has `requirements.txt`, NodeJS has `package.json`).

Interoperability is a more manual assessment and may not scale well, but would be incredibly valuable as a result. Position in the pipeline I am honestly against at the moment given that this will require additional cycles to test and debug - doing this for the search is probably a good test case but I wouldn't want to learn the lessons in two projects at the same time 😅 

---

I would also be happy to have the concrete definition of edges at this time such that we can focus on getting the presentation right. After that, we can always work on expanding the scope of how we define relations and add layers of information as we discover its relevance.

This is all food for discussion - I am not hard set on this.

**Comment by avinashladdha** [comment]
Another potential idea could be clustering of classes/packages for component reuse. One of the expected outcome from this activity is to avoid reinventing the wheel and clustering classes and understanding their functionality could be one good idea.
This is an area of active research --> https://www.sciencedirect.com/science/article/pii/S2212017313006671

I would also vote to get the ball rolling with Dependencies/imports followed by --> clustering and as we start looking at patterns --> interoperability and position in pipeline

**Comment by Bisaloo** [comment]
As discussed last week and in https://github.com/epiverse-connect/epiverse-search/issues/4, one option here could be to compute the map as a 2D projection of the embeddings computed for the search functionality.

This should hopefully match with the intuitive representation / clusters that domain experts would draw.

This is also the logical continuation of the clustering trial @avinashladdha did last year on the CRAN Task View.

**Comment by Bisaloo** [comment]
Conversely, based on my explorations in https://github.com/epiverse-connect/dashboard, dependency relationships do not lead to an easily interpretable output, that could be used to understand the ecosystem from an epidemiological point of view.

![image](https://github.com/epiverse-connect/epiverse-map/assets/10783929/549914fd-339e-4551-ab92-63ed53db362e)

**Comment by Bisaloo** [comment]
I'm closing this issue to document and finalize our choice to have distance represent roughly the semantic proximity of the tools' documentation, with the expectation that this semantic proximity reflects scientific proximity.

Discussion can continue in #10 to determine exactly how the coordinates are computed.
